<h1>User Profile</h1>
<p>Hello, <?=$v($name) // escape the $name variable ?></p>

<div>
  <h2>My Plugin Page Title</h2>
  <form method="post" action="options.php">
    <?php settings_fields( 'myplugin_options_group' ); ?>
    <h3>This is my option</h3>
    <p>Some text here.</p>
    <table>
      <tr valign="top">
        <th scope="row"><label for="webpane_option_name">Secret</label></th>
        <td><input type="text" id="webpane_option_name" name="myplugin_option_name" value="<?php echo get_option('myplugin_option_name'); ?>" /></td>
      </tr>
    </table>
    <?php  submit_button(); ?>
  </form>
</div>
