version: '3.1'

services:

  wordpress:
    build: .
    environment:
      - WORDPRESS_DEBUG=1
      - WORDPRESS_DB_PASSWORD=secret
    ports:
      - 22080:80
    volumes:
      - ./:/app:rw
      - ./wp-content:/var/www/html/wp-content:rw
      - ./:/var/www/html/wp-content/plugins/webpane-wordpress-plugin:rw
      - ./.cache/composer:/root/.composer/cache/:rw
      - ./.cache/composer:/.composer/cache/:rw
    links:
      - mysql
      - adminer

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 22081:8080

volumes:
  mysql:
